### PR TITLE
Alias default idempotency

### PR DESCRIPTION
**Pull request by Lorenzbi**
Make sure setting the default node version is idempotent.

### CODE REVIEW

**Comment by pablocrivella** [comment]
Hello @Lorenzbi, as you can see on the travis build result, this PR is failing.
Is failing bc the alias dir under the nvm root doesn't exist.
Please fix so i can merge it.
And thanks for contributing :smiley: :+1:

**Comment by Lorenzbi** [comment]
Hmm. I'm not too sure this is the right way to go. I wonder if it's possible to register the command output for multiple users and then loop through the results and set the right default. I will update the pull request if I find out how. What do you propose?

**Comment by Lorenzbi** [comment]
hmm after trying to use register I came to the conclusion that I'm probably overthinking the whole thing :)

```yaml
- name: get default version for each user
  shell: bash -lc "nvm alias default"
  register: node_defaults
  sudo: true
  sudo_user: "{{ item }}"
  with_items: nvm_users
 
- name: set {{ nvm_default_node_version }} as default version for each user
  shell: bash -lc "nvm alias default {{ nvm_default_node_version }}"
  when: nvm_default_node_version not in item.1.stdout
  sudo: true
  sudo_user: "{{ nvm_users[item.0] }}"
  with_indexed_items: node_defaults.results
```

I'll add a commit so that the alias directory is created if the user hasn't set an alias already. Less shell, more ansible.

**Comment by Lorenzbi** [comment]
ugh. I should really test this locally. I'll create a new pull request without "fix commits".

**Comment by pablocrivella** [comment]
You can test locally using vagrant, just run ```vagrant up```

**Comment by Lorenzbi** [comment]
Ah nice. :+1:  I'll certainly do that next time.

**Comment by htsplex** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
francishuang, @MagicMikeCoffee, @nfttakerun, @liuguangqiang, @UnknownEnergy, @leiyong1413, @maxbildner, @charles7098, @dimsob, @tcheeric, @JohnnyMa, @mrberti, @plusmancn, @Weizhang2017, @0ihsan, @kevinfeng, @HuWenhai, @vishnu-111, @ahnniu, @mattburman, @mohamedawnallah, @ajax135, @nardsqq, @TableBear, @scorpion9979, @zvrba, @NadalVRoMa, @rigille, @morrxy, @Draichi, @gregoryfm, @alexnaspo, @veektorh, @jean-francoisgiraud, @ilgattong, @Moggi, @caglorithm, @amitkumarusc, @GuyStone, @whitesmell, @siko, @joshickc, @amliu, @krisjin, @satrio-pamungkas, @crouchred, @KanSakamoto, @talipkorkmaz, @jbonsant, @karna0730afdezl, @parsa-ra, @lab0ryu, @camilaavilarinho, @Jravvit, @tnlin, @Coolfield, @XuHugo, @trishmapow, @tonito1101, @promer94, @eadoro1993, @mocusez, @monoppa, @lautarodragan, @DavyLin, @lorien, @ken-miyanabe, @qiqqppip, @crabbykang, @Lvl4Sword, @Joeyinsnow, @yu627482453, @ncanrd, @P1R0H, @aameralduais, @hanguyen-asana, @dbhaskaran, @divay88, @weiwenqiang, @wangyanchang21, @renjianning, @ndongre98, @earizon, @xuing, @violetgo, @bliotti, @true0r, @Gerschel, @SohaibMoinuddin, @hyddox, @TangliziGit, @AlexTan-b-z, @oguzzkilic, @dragon707, @matthias-weston, @mrozigor, @onetthree, @mashford, @demetrios-kozirisColt-M1873, @alphaville-ishii, @pkahly, @allanw, @jdjauhari, @qwendy, @blazingstarz, @KAGITO, @Akaki16, @liuyangc3, @Moozdzn, @mayaugusto7, @gianlucatruda, @YamiTL, @CircleKai, @yaoquan, @seromenho, @EtherBit, @mikezhang3679, @uniqB, @marc-cort, @padilha, @dswwsd, @WuXiao90, @valmassoi, @kwwanjaai, @zhiruiwang, @tailintalent, @radoystoyanov, @wanglf, @LaneaLucy, @angeria, @maschad, @kiyo0718, @sulaimn2, @lucienrey, @karkigrishmin, @Calavan, @coderfi, @exceedhl, @dclsamples, @pigorski, @ScnuWang, @martinma4, @sabarishtm, @mikepitagno, @sunnysul, @ThomasFMH, @foxcool, @cliffxuanfilipaj, @star001007, @jmsncrypto, @c-goosen, @xiaoxiaosen520, @ambaloo, @jackDing2016, @Bigd271, @Bingtuu, @jincai, @brieucdlf, @iamprakhargupta, @AMuppar, @fayelee0, @baohulu, @0lyvi, @neuclid, @Setiadi-Github, @nickbouldien, @Sandu1213, @wzrzt, @8ad8ird, @toandv, @brunowang, @tauhuang, @COsultan, @ceciliavision, @koshikraj, @ashvini-maurya, @mateo465, @oko-ek, @droidLight, @calebpdx, @yezhenzhao, @sumit5113, @soft5, @BlackDudeLi, @eddvys, @cgaspart, @worldAn, @decimalbell, @Marianagb7, @KristinBZ, @ivanhuanghhh, @IvoX00, @isaguler, @SilvioMessi, @ajdurbin, @ltsantos, @davidbehrendgavdaly, @franjsco, @sassy, @brianjking, @guohaoyu110, @qiyeboy, @jennybehan, @jdmarques, @caitianxiong, @shin4141, @JadeVane, @ruhulamin1398, @dbensik, @hsiaoyi0504, @Keith-CY, @evscott, @Sayrarh, @OceanTu, @guagusi, @didiermis, @StevenBlack, @piyushkumarsingh, @whynotyes, @simonfan, @0xnomy, @dMajoIT, @michael-quinlan, @netqyq, @sertacbirdal, @jlinear, @haasman, @matthewholey, @Creatorjason, @shankarshastri, @sudhindrasajjal, @amanone, @skywinston, @tatwan, @cbsudux, @cross-chain, @adib-the-noob, @biglyan, @STainLessspoon, @aerosol, @burakyilmaz321, @rafajak, @blue119, @liqiangz, @shujer, @bojiangprozhangtai, @yguy08, @mac-code, @heaversm, @fanwenbo, @NicolasSanjaya, @armen-ka, @muratcakmak, @Hann, @Gokulaprakash, @superyyrrzz, @KuanJiang2018, @apuppy, @ramuthumu, @gaharavara, @svella9, @alepop, @mtahna, @HUDongge, @abidpu19, @baselkelziye, @Chen-Xuying, @brenda2880, @130126660, @TimiBolu, @AndrewIammatteo, @felipericieri, @Liontome, @Katrina0406, @yononima, @software-is-life, @anhtranbk, @Yoshishid, @knholland, @wawgoingdad, @zhengshushu, @slimshadeey1, @rcerf, @p0lygun, @lopezdp, @wsadczh, @ooptimism, @stoneworld, @xupengrun, @pranavsawant22, @superjantung, @Hugo-Huang, @idbmb, @mdmohsin7, @SMAMMA22

**Pull request closed without merging**
