### PR TITLE
Fix more broken dynamic includes

### PR DESCRIPTION
**Pull request by farridav**
I was unable to get the play to run with these dynamic includes, so ive abstracted them out.

On another note, we should get travis testing on this role

### CODE REVIEW

**Comment by pablocrivella** [comment]
Which ansible version are you using?
Or how could i reproduce this issue?

**Comment by pablocrivella** [comment]
Also, i agree about adding travis testing.

I've been using https://github.com/nickjj/rolespec for other roles.
Here is the specs repo:
https://github.com/pablocrivella/ansible-roles-specs

If you have a better way its much welcome.

**Comment by farridav** [comment]
I have been using the latest version of ansible, to reproduce the issue, run the play with the variables defined below, I also have a colleague that has run the play with `1.9.1`, we use the following variables:

```
nvm_default_node_version: v0.12.7
nvm_env: system
nvm_version: v0.25.4
nvm_node_versions:
  - v0.12.7
  - v0.10.36
nvm_global_packages:: []
```

I'm very surprised this issue isn't happening to you, as it doesn't seem tied to my setup... happy to hear your thoughts

**Comment by farridav** [comment]
RE: testing, a good approach can be seen here https://github.com/ANXS/postgresql

**Comment by pablocrivella** [comment]
Hey @farridav, i just ran the playbook and i didn't get any errors :confused: 
```
TASK: [pablocrivella.nvm | include_vars {{ nvm_env }}.yml] ********************
ok: [js]

TASK: [pablocrivella.nvm | checkout nvm_repo] *********************************
changed: [js]

TASK: [pablocrivella.nvm | add nvm initialization to profile] *****************
changed: [js]

TASK: [pablocrivella.nvm | install versions] **********************************
changed: [js] => (item=v0.12.7)
changed: [js] => (item=v0.10.36)

TASK: [pablocrivella.nvm | set {{ nvm_default_node_version }} as default version] ***
changed: [js]

TASK: [pablocrivella.nvm | install packages] **********************************
changed: [js] => (item=['v0.12.7', 'bower'])
changed: [js] => (item=['v0.10.36', 'bower'])
```

**Pull request merged**
